name: 🤖

on:
  issue_comment:
    types: [created]

jobs:
  command:
    if: startsWith(github.event.comment.body, '/')
    runs-on: ubuntu-latest
    steps:
      - name: Output issue command
        run: echo "${{ github.event.comment.body }}"
      
