name: 🧮 Matrix Job Results

on: workflow_dispatch

jobs:
  first:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        node: [10, 12, 14]
    steps:
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - run: printenv|sort
  first-status:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: Check first matrix status
        if: ${{ needs.first.result != 'success' }}
        run: exit 1
