name: ✉️ Testing post actions

on:
  workflow_dispatch:

jobs:
  step-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run action with true env
        uses: ./action
        env:
          SKIP_POST: true
      - name: Run action with false env
        uses: ./action
        env:
          SKIP_POST: false
      - name: Run action without env
        uses: ./action
  job-env:
    runs-on: ubuntu-latest
    env:
      SKIP_POST: true
    steps:
      - uses: actions/checkout@v2
      - name: Run action with job env
        uses: ./action