name: To Lower

on: workflow_dispatch

jobs:
  lower:
    runs-on: ubuntu-latest
    steps:
    - name: Lowercase a context value
      id: lowercase
      run: |
        echo "::set-output name=value::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')"
      shell: bash

    - name: Using the output value
      run: echo "${{ steps.lowercase.outputs.value }}" # steps.STEP_ID.outputs.OUTPUT_NAME