name: CI

on: [push]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@joshmgross/log-node-version
      with:
        node-version: '12.x'
